---
title: try catch finally 错误捕获
---
## `finally`子句总会在 `try catch`后执行

<<<  @/playground/js/try_catch_finally/demo1.js

## `return`与`try{}catch(){}finally{} ...`语句的关系

### 在没有return语句的时候， `try catch finally`后的代码能够执行

<<<  @/playground/js/try_catch_finally/demo2.js

### `finally`中的字句中的`return`会覆盖 `try catch`中的return 

<<<  @/playground/js/try_catch_finally/demo3.js
